#!/usr/bin/env python3
"""Generate a compact C++ header from a calibration JSON
(`tools/show_colors_video.json`) for embedding into the bridge
firmware. The header exposes:

    namespace esphome { namespace colorsplash_xg {
      struct LutSample {
        uint8_t  start_byte;
        uint16_t wait_ms;
        uint8_t  r, g, b;
      };
      extern const LutSample SHOW_LUT[];
      extern const size_t    SHOW_LUT_LEN;
      struct SolidEntry {
        uint8_t  start_byte;
        uint8_t  r, g, b;
      };
      extern const SolidEntry SOLID_LUT[];
      extern const size_t     SOLID_LUT_LEN;
      extern const uint8_t   AMBIENT_R, AMBIENT_G, AMBIENT_B;
    } }

The picker C++ code does a Euclidean RGB distance search across
both arrays.

Decimation: by default we take one sample every 100 ms, which for
7 shows × 90 s = 6300 samples raw → 630 samples decimated → ~5 KB.
Adjust --interval-ms for a different size/precision tradeoff.

Usage:
    python tools/generate_show_lut.py \\
        --in tools/show_colors_video.json \\
        --out firmware/esphome/components/colorsplash_xg/show_color_lut.h
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


SOLID_BYTES = {
    "Parisian Blue": 0x08,
    "Brazilian Red": 0x0a,
    "Arctic White": 0x0b,
    "Miami Pink": 0x0c,
    "New Zealand Green": 0x09,
}

SHOW_BYTES = {
    "Nova": 0x07,
    "Super Nova": 0x02,
    "Northern Lights": 0x03,
    "Tidal Wave": 0x04,
    "Patriot Dream": 0x05,
    "Desert Skies": 0x06,
    "Peruvian Paradise": 0x01,
}


def decimate(samples: list[dict], interval_ms: int,
             skip_ms: int) -> list[dict]:
    """Return one sample per `interval_ms` window, starting at
    `skip_ms`. Picks the sample whose t_ms is closest to each grid
    point so the kept colours track real fixture state."""
    if not samples:
        return []
    samples_sorted = sorted(samples, key=lambda s: s["t_ms"])
    max_t = samples_sorted[-1]["t_ms"]
    grid = list(range(skip_ms, max_t + 1, interval_ms))
    out = []
    cursor = 0
    for g in grid:
        # advance cursor while next sample is still closer to g
        while (cursor + 1 < len(samples_sorted)
               and abs(samples_sorted[cursor + 1]["t_ms"] - g)
               <= abs(samples_sorted[cursor]["t_ms"] - g)):
            cursor += 1
        out.append(samples_sorted[cursor])
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--in", dest="inp",
                   default="tools/show_colors_video.json", type=Path)
    p.add_argument("--out", required=True, type=Path)
    p.add_argument("--interval-ms", type=int, default=100,
                   help="decimation interval (default 100 — one "
                        "sample every 100 ms per show)")
    p.add_argument("--skip-ms", type=int, default=2500,
                   help="exclude samples earlier than this (default "
                        "2500 — covers BLE+dispatch latency)")
    args = p.parse_args()

    data = json.loads(args.inp.read_text())

    # ---- Show samples (decimated) ----
    show_entries: list[tuple[int, int, int, int, int]] = []
    show_summary: list[tuple[str, int]] = []
    for show_name, samples in data.get("shows", {}).items():
        base = show_name.split(" #")[0]
        if base not in SHOW_BYTES:
            continue
        byte = SHOW_BYTES[base]
        decimated = decimate(samples, args.interval_ms, args.skip_ms)
        show_summary.append((base, len(decimated)))
        for s in decimated:
            r, g, b = s["rgb"]
            show_entries.append(
                (byte, int(s["t_ms"]), r, g, b))

    # ---- Solids ----
    solid_entries: list[tuple[int, int, int, int]] = []
    for name, rgb in data.get("solids", {}).items():
        if name not in SOLID_BYTES:
            continue
        r, g, b = rgb
        solid_entries.append((SOLID_BYTES[name], r, g, b))

    # ---- Ambient ----
    ambient = data.get("ambient_rgb") or [0, 0, 0]
    ar, ag, ab = ambient

    # ---- Header text ----
    lines = []
    lines.append("// Auto-generated by tools/generate_show_lut.py")
    lines.append(f"// Source: {args.inp}")
    lines.append(f"// Generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}")
    lines.append(f"// Decimation: 1 sample per {args.interval_ms} ms, "
                 f"skip first {args.skip_ms} ms.")
    lines.append("//")
    lines.append("// DO NOT EDIT — regenerate with:")
    lines.append(f"//   python tools/generate_show_lut.py --in {args.inp} "
                 f"--out {args.out}")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append("namespace esphome {")
    lines.append("namespace colorsplash_xg {")
    lines.append("")
    lines.append("struct LutSample {")
    lines.append("  uint8_t  start_byte;")
    lines.append("  uint32_t wait_ms;  // up to 90s — uint16 overflows")
    lines.append("  uint8_t  r, g, b;")
    lines.append("};")
    lines.append("")
    lines.append("struct SolidEntry {")
    lines.append("  uint8_t  start_byte;")
    lines.append("  uint8_t  r, g, b;")
    lines.append("};")
    lines.append("")

    lines.append(f"// Per-show samples — {len(show_entries)} entries:")
    for name, n in show_summary:
        lines.append(f"//   {name:22s}: {n} samples")
    lines.append("constexpr LutSample SHOW_LUT[] = {")
    for byte, t, r, g, b in show_entries:
        lines.append(f"  {{0x{byte:02x}, {t:6d}, {r:3d}, {g:3d}, {b:3d}}},")
    lines.append("};")
    lines.append(f"constexpr size_t SHOW_LUT_LEN = "
                 f"sizeof(SHOW_LUT) / sizeof(SHOW_LUT[0]);")
    lines.append("")

    lines.append(f"// Solids — {len(solid_entries)} entries (one per "
                 "documented solid preset):")
    lines.append("constexpr SolidEntry SOLID_LUT[] = {")
    for byte, r, g, b in solid_entries:
        lines.append(f"  {{0x{byte:02x}, {r:3d}, {g:3d}, {b:3d}}},")
    lines.append("};")
    lines.append(f"constexpr size_t SOLID_LUT_LEN = "
                 f"sizeof(SOLID_LUT) / sizeof(SOLID_LUT[0]);")
    lines.append("")

    lines.append("// Ambient (Standby) baseline — the camera reading "
                 "with the fixture off.")
    lines.append("// Used by the picker as a 'this colour is "
                 "unreachable' floor.")
    lines.append(f"constexpr uint8_t AMBIENT_R = {ar};")
    lines.append(f"constexpr uint8_t AMBIENT_G = {ag};")
    lines.append(f"constexpr uint8_t AMBIENT_B = {ab};")
    lines.append("")
    lines.append("}  // namespace colorsplash_xg")
    lines.append("}  // namespace esphome")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    sz = args.out.stat().st_size
    print(f">>> wrote {args.out} ({sz} bytes, "
          f"{len(show_entries)} show samples + "
          f"{len(solid_entries)} solids)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
